#!/usr/bin/env bash

## SETUP
spec_root=$(dirname ${BASH_SOURCE[0]})
source $spec_root/../lib/shpec

describe "shpec"
  describe "basic operations"
    it "asserts equality"
      assert equal "foo" "foo"

    it "asserts partial matches"
      assert match "partially" "partial"

    it "asserts blankness"
      assert blank ""
  end_describe

  describe "passing through to the test builtin"
    it "asserts an arbitrary integer test"
      assert true "[[ 5 -lt 10 ]]"

    it "asserts an arbitrary string test"
      assert true "[[ 'foo' != 'bar' ]]"
  end_describe

  describe "testing files"
    it "can test file existence"
      assert true "[[ ! -e /tmp/foo ]]"

    it "can verify that a file was created"
      touch /tmp/foo
      assert true "[[ -e /tmp/foo ]]"
      rm /tmp/foo

    it "can verify the pointer of a symlink"
      ln -s $HOME /tmp/link
      assert equal "$(readlink /tmp/link)" "$HOME"
      rm /tmp/link
  end_describe

  describe "exit codes"
    it "returns nonzero if any test fails"
      ./$spec_root/etc/failing_example &> /dev/null
      assert true "[[ $? -ne 0 ]]"

    it "returns zero if a suite passes"
      ./$spec_root/etc/passing_example &> /dev/null
      assert true "[[ $? -eq 0 ]]"
  end_describe
end_describe
